theme: jekyll-theme-minimal
permalink: pretty
name: Lily Tabs
url: www.lilytabs.com

nav-background: #B40604
nav-font: #fff
jumbotron-background: #ECEEEF
jumbotron-font: #fff

collections:
  tabs:
    output: true
    permalink: /:path
