theme: jekyll-theme-minimal
permalink: pretty
name: Tabs
url: https://krussll.github.io/tabs/

nav-background: #B40604
nav-font: #fff
jumbotron-background: #ECEEEF
jumbotron-font: #fff

collections:
  tabs:
    output: true
    permalink: /:path
